services:
  frontend:
    image: ashokstack/cosmic_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

  backend:
    image: ashokstack/cosmic_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://ashokstack:ashok3182004@cluster0.uo5sr.mongodb.net/food-del
    depends_on:
      - mongo

  admin:
    image: ashokstack/cosmic_admin
    ports:
      - "4000:3000"

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
