version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb+srv://ashokstack:ashok3182004@cluster0.uo5sr.mongodb.net/food-del
    depends_on:
      - mongo

  admin:
    build: ./admin
    ports:
      - "4000:3000"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
